use std::fmt::Debug;

#[derive(Debug)]
/// An enum representing errors that can occur when reading data from a `BitSource`.
/// 
/// A general error is that the end of the source has been reached (you are
/// attempting to read more data than was written, so some data is missing). The
/// `ReachedEnd` error is used to indicate this situation.
/// 
/// Also, there can be implementation specific errors generated by the `BitSource`,
/// which can be of any type that implements `Debug`. The `Other` error is used to
/// indicate this.
pub enum ReadError {

    ReachedEnd{ read_bools: usize },

    Other(Box<dyn Debug>)
}